console.log('hello world');
const nameOurPlanet = "earth";
console.log(nameOurPlanet);
let usersCurrentTime = "1:56";
console.log(usersCurrentTime);
let titleArticle = "25";
console.log(titleArticle);
const cashOrNotCashPayment = ("yes");
console.log(cashOrNotCashPayment);
let name = ("Sergey");
console.log(name);
let familyName = ("Panamarev");
console.log(familyName);
let patronymic = ("Pavlovich");
console.log(patronymic);
